### ISSUE TITLE
Angular beginner issues.

### ISSUE THREAD

**Issue by elesniewski** [Bigless27/Angular-webpack-starter#1]
Use this template below for bugs.

In trying to follow along with the video tutorial and provided files for download, users will run into numerous problems. 2 of the 3 problems mentioned here have remedies as provided.  With limited understanding of Angular environment setup, the 3rd problem becomes a 'halt'.
## Expected Behavior

One can expect to copy command-line examples as provided by instructor with successful output, mirroring the instructors video.
## Current Behavior

First issue: 
TS2304: Cannot find name ‘require’ ERROR in [at-loader] in ./src/app/app.component.ts and ./src/polyfills.ts

Second issue: 
There is also the following error while running ‘npm run webpack-prod’:
‘output.filename’ is required, either in config file or as --output-filename.

Third issue: 
ERROR in chunk app [initial]
webpack.prod.js
Conflict: Multiple assets emit to the same filename webpack.prod.js

ERROR in chunk polyfills [entry]
webpack.prod.js
Conflict: Multiple assets emit to the same filename webpack.prod.js
## Possible Solution

Issue one: 
This I can fix by placing the following in tsconfig.json and tsconfig-aot.json compilerOptions section:
“typeRoots”: [
“node_modules/@types”
]

Issue two: 
This I can fix by changing the syntax of the command to: 'npm run webpack-prod --config config/webpack.prod.js

Issue three:
Beyond the scope of a user trying to learn from a video tutorial.

## Steps to Reproduce

1. Setup in a Windows environment
2. Begin learning Angular from the 'Heroes' tutorial found at https://angular.io/tutorial
3. Have relatively recent versions of dependencies
4. This is all that I know about Angular at the moment.

## Context (Environment)

I am trying to understand the Uglify section of the tutorial which bundles the .js files to compare size in production section of tutorial.

Angular beginner issues.
## Detailed Description

It also may be helpful to explain what helper.js file is and what the .gitignore file is for
## Possible Implementation

Comments under the video, or a video overlay with current instructions/fixes would be helpful

**Comment by Bigless27** [comment]
Hey @elesniewski!

I just pushed up fixes for everything. Feel free to pull them down and test them out yourself. I do apologize for missing these things during the tutorial! I'm still newer to creating my own tutorials and will just keep getting better at them in time. 

 1. The first issue is an interesting one that I experienced in a project before this. The gist of it is all @type files should be automatically visible to tsconfig. This works on mac but looks like it doesn't work on windows. I assumed the newest version of awesome-typescript-compiler would solve this but I guess not. I added the explicit paths to the corresponding @type files per your suggestion.

2. This is just me missing something by accident. I forgot to add an output path to the webpack-prod.js file. Please, find the new output config there.

3. Finally, this I believe happened because `npm run webpack-prod` already looks for the webpack-prod file. The --config flag tells it to explicitly look for that which I'm assuming this is why it is erroring.

Again I do apologize for missing these things and I thank you so much for opening this issue. Please let me know if anything else arrises, and I would be glad to fix them for you!

Lesson on Coding(Ryan Lesson)

**Comment by elesniewski** [comment]
Good Job! Webpack-prod compiles the bundles now. Thanks!  I will follow through to the end of tutorial this evening.

 

Eric
